# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env: 
  path: /home/BO/services/mentor/nginx/html/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js '12.x'
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - name: delete old
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.host }}
        username: ${{ secrets.username }}
        password: ${{ secrets.pwd }}
        envs: path
        script: rm -rf ${{ env.path }}*
    - name: copy file
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.host }}
        username: ${{ secrets.username }}
        password: ${{ secrets.pwd }}
        source: "dist/"
        envs: path
        target: ${{ env.path }}
        strip_components: 1


